export const actionTypes = {
    // Reducers
    USER_LOGIN_SUCCEEDED: "USER_LOGIN_SUCCEEDED",
    USER_CREATE_SUCCEEDED: "USER_CREATE_SUCCEEDED",
    USER_LIST_SUCCEEDED: "USER_LIST_SUCCEEDED",
    USER_FAILED: "USER_FAILED"
};
